spring.application.name=driver-vehicle-service
server.port=8082

spring.config.import=optional:file:.env[.properties]

spring.data.mongodb.uri=${MONGODB_URI_DRIVER:mongodb://localhost:27017/ridelink_driver_vehicle_service}
spring.mongodb.uri=${MONGODB_URI_DRIVER:mongodb://localhost:27017/ridelink_driver_vehicle_service}
spring.mongodb.database=ridelink_driver_vehicle_service

app.jwt.secret=${JWT_SECRET}
app.jwt.issuer=ridelink-account-service
app.jwt.audience=ridelink-services

app.internal.service-key=${INTERNAL_SERVICE_KEY}

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html