spring.application.name=account-service
server.port=8081

spring.config.import=optional:file:.env[.properties]

spring.mongodb.uri=${MONGODB_URI}
spring.mongodb.database=ridelink_account_service



app.jwt.secret=${JWT_SECRET}
app.jwt.issuer=ridelink-account-service
app.jwt.audience=ridelink-services
app.jwt.expiration-seconds=3600



app.bootstrap-admin.enabled=${ADMIN_BOOTSTRAP_ENABLED:false}
app.bootstrap-admin.full-name=${ADMIN_FULL_NAME:}
app.bootstrap-admin.email=${ADMIN_EMAIL:}
app.bootstrap-admin.password=${ADMIN_PASSWORD:}